baseURL = 'https://blog.datsuraku147.org'
languageCode = 'en-us'
title = "Crong's Blog"
pluralizelisttitles = false

[taxonomies]
  tag = "tags"
  category = "categories"

[menu]
    # The page reference (pageRef) is useful for menu highlighting
    # When pageRef is set, setting `url` is optional; it will be used as a fallback if the page is not found.
  [[menu.main]]
    name = "Categories"
    pageRef = "categories"
    weight = 10
  [[menu.main]]
    name = "Tags"
    pageRef = "tags"
    weight = 20
  [[menu.main]]
    name = "Timeline"
    pageRef = "timeline"
    weight = 30
  [[menu.main]]
    name = "Me???"
    pageRef = "crong"
    pluralizeListTitles = false
    weight = 40

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

[params]

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # set theme to full screen width
  fullWidthTheme = true

  # center theme with default width
  centerTheme = true

  defaultColor = "dark" # set default color mode: dark or light or auto 
  description = "Datsuraku's blog"
  mainSections = ['timeline']
  toc = true # set to false to disable table of contents 'globally'
  goToTop = true # set to false to disable 'go to top' button

[params.author]
  avatar = "crong.png" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Personal Blog - writeups/research/life"
  name = "Datsuraku"
  description = "Posting anything I want to share here :D"

[[params.socialIcons]]
name = "github"
url = "http://github.com/datsuraku147"

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/MDatsuraku"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"


